platform :ios, '7.0'
pod 'MJRefresh', '> 3.0.0'
pod 'AFNetworking', '>= 3.0'
pod 'SVProgressHUD'
pod 'UITableView+FDTemplateLayoutCell'
pod 'FDFullscreenPopGesture'
pod "YYCache"
pod 'MJExtension'
pod 'SDWebImage'
